version: '3.2'

services:
  docker-mysql:
    image: mysql
  #  volumes:
    #   - micro1-volume:/var/lib/mysql/micro1
    environment:
      - MYSQL_ROOT_PASSWORD=26156276
      - MYSQL_DATABASE=micro1
      - MYSQL_PASSWORD=26156276
  

  micro1-app-jenk:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    links:
        - docker-mysql:mysql
    ports:
      - 8085:8085
  #  volumes:
   #     - micro1-volume:/var/lib/mysql/micro1
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/micro1?useSSL=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=26156276
      #- DATABASE_HOST=docker-mysql
      #- DATABASE_USER=root
      #- DATABASE_PASSWORD=26156276
     # - DATABASE_NAME=micro1
      #- DATABASE_PORT=3306
      
# volumes:
  # micro1-volume:
