version: '3'

services:
  docker-mysql:
    build:
      context: ./src/main/resources
      dockerfile: Dockerfile
    volumes:
        - ./src/main/resources:/docker-entrypoint-initdb.d
 

  micro1-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    links:
      - docker-mysql:mysql
    ports:
      - 8085:8085
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql/micro1?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=26156276
   
